[book]
authors = ["troyerta"]
language = "en"
multilingual = false
description = "The example book covers recipes."
src = "src"
title = "Recipes"
create-missing = false

[output.html.fold]
enable = true
level = 1
